### ISSUE TITLE
Permission denied for /.cache

### ISSUE THREAD

**Issue by ccremer** [bitnami/bitnami-docker-golang#7]
### Name and Version

bitnami/golang:1.18

### What steps will reproduce the bug?

```
$ docker run --rm -v ${PWD}:/go/src -u $(id -u) bitnami/golang:1.18 go run src/<file>
failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied
```

### What is the expected behavior?

`go run` should be able to run the code with an arbitrary user ID.

### What do you see instead?

Container exits with error
```
failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied
```

### Additional information

I thought I could choose the `bitnami/go` image over docker's official image `go:latest` since usually I made the experience that Bitnami images also work as non-root user. This doesn't seem to be the case though?

NOTE: The image seems to work when setting the cache env to the `/go` dir, for example
```
docker run --rm -v ${PWD}:/go/src -u $(id -u) -e GOCACHE=/go/.cache/go-build bitnami/golang:1.18 go run src/<file>
```

**Comment by alemorcuq** [comment]
Hi, @ccremer!

Thanks for reporting this. What do you think about setting `GOCACHE` by default to `/go/.cache` in the image?

**Comment by ccremer** [comment]
Hi @alemorcuq 
That would work for me, but I can't speak for the whole community :)

**Comment by alemorcuq** [comment]
We released three new images (one per branch) setting `GOCACHE` to `/go/.cache`. Thank you again for reporting this.
